vich_uploader:
    db_driver: orm

    mappings:
        upload_images:
            uri_prefix: '%upload_images%'
            upload_destination: '%kernel.project_dir%/public%upload_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
